name: CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo, pdo_mysql

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Storage Permission
        run: chmod -R 777 storage bootstrap/cache

  test:
    name: ✅ Test
    needs: build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo, pdo_mysql

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Step 1: Run Initial Migrations Only
      - name: Initial Migration
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
        run: |
          php artisan migrate --path=/database/migrations/2014_10_12_000000_create_users_table.php
          php artisan migrate --path=/database/migrations/2014_10_12_100000_create_password_reset_tokens_table.php
          php artisan migrate --path=/database/migrations/2019_08_19_000000_create_failed_jobs_table.php
          php artisan migrate --path=/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
          php artisan migrate --path=/database/migrations/2024_10_02_123932_laratrust_setup_tables.php
          php artisan migrate --path=/database/migrations/2024_10_03_044644_add_atribut_users.php

      # Step 2: Run Roles Table Seeder
      - name: Run Roles Table Seeder
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
        run: php artisan db:seed --class=RolesTableSeeder

      # Step 3: Run Remaining Migrations
      - name: Full Migration and Seed
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
        run: |
          php artisan migrate --path=/database/migrations
          php artisan db:seed

      - name: Execute Tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
        run: php artisan test

  deploy:
    name: 🚀 Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy code via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
