name: 🚀 Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo, pdo_mysql

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Storage Permission
        run: chmod -R 777 storage bootstrap/cache

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo, pdo_mysql

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Initial Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
        run: |
          php artisan migrate --path=/database/migrations/2014_10_12_000000_create_users_table.php --force
          php artisan migrate --path=/database/migrations/2014_10_12_100000_create_password_reset_tokens_table.php --force
          php artisan migrate --path=/database/migrations/2019_08_19_000000_create_failed_jobs_table.php --force
          php artisan migrate --path=/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php --force
          php artisan migrate --path=/database/migrations/2024_10_02_123932_laratrust_setup_tables.php --force
          php artisan migrate --path=/database/migrations/2024_10_03_044644_add_atribut_users.php --force

      - name: Run Roles Table Seeder
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
        run: php artisan db:seed --class=RolesTableSeeder --force

      - name: Full Migration
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
        run: php artisan migrate --force
      
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run Dusk Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: passw0rd
          APP_URL: http://127.0.0.1:8000
        run: php artisan dusk

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Deploy code via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          debug: true
