on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    # Step 1: Checkout the repository
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Step 2: Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql, bcmath, soap, intl, gd, exif, iconv

    # Step 3: Copy .env file
    - name: Copy .env file
      run: cp .env.example .env

    # Step 4: Install dependencies
    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Step 5: Generate application key
    - name: Generate key
      run: php artisan key:generate

    # Step 6: Set storage permissions
    - name: Set storage permissions
      run: chmod -R 777 storage bootstrap/cache

    # Step 7: Wait for MySQL to be ready
    - name: Wait for MySQL to be ready
      run: sleep 15

    # Step 8: Run database migration and seeding
    - name: Run migrations and seed database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: passw0rd
      run: php artisan migrate:fresh --seed

    # Step 9: Run tests (Unit and Feature tests)
    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: passw0rd
      run: php artisan test

    # Step 10: Deploy via FTP
    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
