name: 🚀 Deploy website on push

on: 
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2
        coverage: none

    # Install dependencies (Composer)
    - name: Install Composer dependencies
      run: composer install

    # Run PHPUnit tests
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --configuration phpunit.xml

    # Deploy the website via FTP
    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
